name: Performance Baseline

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  performance:
    name: Performance Test
    runs-on: ubuntu-latest
    environment:
      name: Integration
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: bash .github/golden-path/performance-test.sh
