name: Performance Baseline

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  performance:
    name: Performance Test
    runs-on: ubuntu-latest
    environment:
      name: Integration
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - run: bash .github/golden-path/performance-test.sh
