name: Security Scanning

on:
  pull_request:
  push:
    branches:
      - main
      - "release-*"
  schedule:
    - cron: "23 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  security:
    name: Security Scanning
    if: github.event_name != 'push' || github.event.created == false
    uses: JSL-Inc/golden-path-workflows-v2/.github/workflows/reusable-security.yml@v2
    with:
      languages: '["python"]'
