name: System Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  readiness:
    name: Environment Readiness
    runs-on: ubuntu-latest
    environment:
      name: QA
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - run: bash .github/golden-path/system-test.sh
